spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: wlxx-eureka
  devtools:
    restart:
      enabled: true
    add-properties: false
  cloud:
    config:
      enabled: false

server:
  port: 12000

eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
  client:
    #由于自己就是服务器，不需要注册到自己
    register-with-eureka: true
    #由于自己就是服务器，不需要从服务器获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka



logging:
  level:
    root: info