spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: xiao
  application:
    name: auth
#  cloud:
#    nacos:
#      enable: false
#      server-addr: 127.0.0.1:8848
#      discovery:
#        namespace: public
#        register-enabled: false
  security:
    user:
      name: admin
      password: admin
      roles: admin

server:
  port: 18083