version: "3.0"
services:
  wlxx-system:
    container_name: wlxx-system
    #    nacos正对mysql做了优化，无法直接使用MySQL原版镜像
    image: wlxx-system-provider:0.0.1-SNAPSHOT
    # image: nacos/nacos-mysql:8.0.16
    environment:
#      - DATASOURCE_URL=192.168.100.237
      - DATASOURCE_URL=mysql # 同一个网络下，通过实例名称访问
      - NACOS_ADDR=nacos
    privileged: true
    ports:
      - "8080:8080"
    restart: always
    networks:
      - wlxx-docker_default

# 指定使用外部网络
networks:
  wlxx-docker_default:
    external: true
    driver: bridge