version: "3.0"
services:
  wlxx-system:
    container_name: wlxx-system
    image: wlxx-system-provider:0.0.1-SNAPSHOT
    environment:
      - DATASOURCE_URL=mysql # 同一个网络下，通过实例名称访问
      - NACOS_ADDR=nacos
      - REDIS_HOST=redis
    privileged: true
    ports:
      - "12000:12000"
#    restart: always
    networks:
      - wlxx-docker_default
  wlxx-user:
    container_name: wlxx-user
    image: wlxx-user-provider:0.0.1-SNAPSHOT
    environment:
      - DATASOURCE_URL=mysql # 同一个网络下，通过实例名称访问
      - NACOS_ADDR=nacos
      - REDIS_HOST=redis
    privileged: true
    ports:
      - "12001:12001"
    networks:
      - wlxx-docker_default

# 指定使用外部网络
networks:
  wlxx-docker_default:
    external: true
    driver: bridge