spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL:localhost}:3306/${SCHEMA_NAME:db_org}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

server:
  port: 12002

logging:
  level:
    root: info
    com.xzg.wlxx: debug
  file:
    # 日志文件名格式
    name: "logs/${spring.application.name}.log"
    pattern:
      # 日志记录格式[组件名称] [时间戳] [日志级别] [类名.方法名] [消息文本]
      file: "${spring.application.name} %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n"
    logback:
      rollingpolicy:
        # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
        file-name-pattern: "%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz"
        # 最大日志文件大小(默认为10MB，这里为了测试归档，暂时设置为2KB)
        max-file-size: 2KB
        # 要保留的日志备份的总大小(默认为0B)
        total-size-cap: 1GB
        # 保存存档日志文件的最大天数(默认为7天)
        max-history: 20


