spring:
  datasource:
    spring:
      datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:h2:mem:test
    hikari:
      # HikariPool 需要使用 jdbc-url
      wlxx:
        jdbc-url: jdbc:mysql://47.110.139.158:3306/wlxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: wlxx
        password: xiao
      auth:
        jdbc-url: jdbc:mysql://47.110.139.158:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: auth
        password: xiao
  devtools:
    remote:
      restart:
        enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#  关闭校验BPS检查bpmn文件的校验
  activiti:
    check-process-definitions: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8090

logging:
  level:
    root: info

#关闭activiti安全验证
security:
  basic:
    enabled: false