spring:
  application:
    name: wlxx-user
  datasource:
    url: jdbc:mysql://localhost:3306/db_config?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: xiao

mybatis-plus:
  type-handlers-package: com.xzg.wlxx.common.core.mybatis.handler
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    refresh: true
    activeRecord: true # FIXME 这个怎么开启？是否是因为分离式模块导致无法编译到entity？activeRecord模式不支持hikari多数据源？
    db-config:
      id-type: ASSIGN_UUID #主键类型  全局唯一ID，内容为空自动填充（默认配置），对应数字 2
      field-strategy: 1 #字段策略 IGNORED-0:"忽略判断",NOT_NULL-1:"非 NULL 判断"),NOT_EMPTY-2:"非空判断"
      db-column-underline: true #表名、字段名、是否使用下划线命名
      capital-mode: false #是否大写命名
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除注入器
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true #下换线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
