spring:
  application:
    name: consumer
  cloud:
    nacos:
      config:
      server-addr: 127.0.0.1:8848
      discovery:
        register-enabled: false
        namespace: public

server:
  port: 18082