USE AUTH;

-- 菜单表
DROP TABLE IF EXISTS T_MENU;
CREATE TABLE T_MENU(
    ID VARCHAR(64) PRIMARY KEY,
    MENU_NAME VARCHAR(64),
    ICON VARCHAR (128),
    PATH VARCHAR(200),
    SORT INT,
    PARENT_ID VARCHAR(64)-- 父级ID
);

-- 用户表
DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER(
    ID VARCHAR(64) PRIMARY KEY,
    USERNAME VARCHAR(128),
    LOGINNAME VARCHAR(128),
    PASSWORD VARCHAR(128),
)