use wlxx;

DROP TABLE IF EXISTS T_DICT;
CREATE TABLE T_DICT(
    ID VARCHAR(128) PRIMARY KEY,
    CREATE_TIME DATETIME,
    CREATE_USER VARCHAR(128),
    UPDATE_TIME DATETIME,
    UPDATE_USER VARCHAR(128),

    DICT_ID VARCHAR(128),
    IS_DICT_ROOT INT NOT NULL DEFAULT 0,
    DESCRIPTION VARCHAR(512),

    DICT_CODE VARCHAR(128) NOT NULL,
    DICT_NAME NVARCHAR(128) NOT NULL,
    

    STATE INT NOT NULL DEFAULT 1,
);

