use wlxx;

DROP TABLE IF EXISTS T_CHAR;
CREATE TABLE T_CHAR (
    CODE int(11) NOT NULL,
    ASCII_CODE int(11) DEFAULT NULL,
    HEX_CODE varchar(64) DEFAULT NULL,
    C varchar(32) DEFAULT NULL,
    PRIMARY KEY (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ALTER TABLE wlxx.t_char MODIFY COLUMN CODE int(11) auto_increment NOT NULL;

