version: "3.0"
services:
  mysql:
    container_name: mysql
    #    nacos正对mysql做了优化，无法直接使用MySQL原版镜像
    image: mysql:latest
    # image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./mysql/mysql.env
    privileged: true
    volumes:
      - ${DATA_PATH}/mysql/data:/var/lib/mysql
      - ${DATA_PATH}/mysql/log:/var/log/mysql
      - ${DATA_PATH}/mysql/mysql-files:/var/lib/mysql-files/
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
      # - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/config:/etc/mysql
    ports:
      - "3306:3306"
    restart: always
  nacos:
    container_name: nacos-server
    image: nacos/nacos-server:${NACOS_VERSION}
    #    environment:
    #      - SPRING_DATASOURCE_PLATFORM=mysql
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    volumes:
      - ${DATA_PATH}/nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3.9-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
      - "3680:3680"
    volumes:
      - ./redis/redis/redis.conf:/etc/redis/redis.conf
      - ${DATA_PATH}/redis/data:/data
    command: /bin/bash -c "redis-server /etc/redis/redis.conf --appendonly yes --requirepass Htan_123redis"
  # #    TODO sentinel
  # sentinel:
  #   container_name: sentiinel
  #   image: bladex/sentinel-dashboard
  #   environment:
  #     - SENTINEL_DOWN_AFTER=5000
  #     - SENTINEL_FAILOVER=5000
  #   ports:
  #     # 默认访问端口
  #     - "9901:8858"
  # seata:
  #   container_name: seata
  #   image: seataio/seata-server
  #   hostname: seata
  #   ports:
  #     - "8091:8091"
  #   environment:
  #     - SEATA_PORT=8091
  #     - STORE_MODE=file
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ${DATA_PATH}/nginx:/etc/nginx
  #   ports:
  #     - "80:80"
    # frontend
#    dolores:
#      container_name: dolores
#      image: rapteam/rap2-dolores:latest
#      ports:
#        #冒号前可以自定义前端端口号，冒号后不要动
#        - 3000:38081
#    # backend
#    delos:
#      container_name: delos
#      image: rapteam/rap2-delos:latest
#      ports:
#        # 这里的配置不要改哦
#        - 38080:38080
#      environment:
#        - SERVE_PORT=38080
#        # if you have your own mysql, config it here, and disable the 'mysql' config blow
#        - MYSQL_URL=mysql # links will maintain /etc/hosts, just use 'container_name'
#        - MYSQL_PORT=3306
#        - MYSQL_USERNAME=root
#        - MYSQL_PASSWD=xiao
#        - MYSQL_SCHEMA=rap2
#
#        # redis config
#        - REDIS_URL=redis
#        - REDIS_PORT=6379
#
#        # production / development
#        - NODE_ENV=production
#      ###### 'sleep 30 && node scripts/init' will drop the tables
#      ###### RUN ONLY ONCE THEN REMOVE 'sleep 30 && node scripts/init'
#      command: /bin/sh -c 'node dispatch.js'
#      # init the databases
#      # command: sleep 30 && node scripts/init && node dispatch.js
#      # without init
#      # command: node dispatch.js
#      depends_on:
#        - redis
#        - mysql
