#datasource:
#  jndi:
#    resource-ref: ''
#email:
#  use-credentials: ''
flowable:
  admin:
    app:
      data-source-prefix: ''
      security:
        encryption:
          credentials-i-v-spec: ''
          credentials-secret-spec: ''
        preemptive-basic-authentication: ''
      server-config:
        process:
          context-root: ${spring.application.name}
  async-executor-activate: ''
  common:
    app:
      cache-login-tokens:
        max-age: 30
        max-size: 2048
      cache-login-users:
        max-age: 30
        max-size: 2048
      cache-users:
        max-age: 30
        max-size: 2048
      idm-admin:
        password: 'xiao'
        user: 'admin'
      idm-redirect-url: ''
      idm-url: ''
      redirect-on-auth-success: ''
      role-prefix: ''
      tenant-id: ''
  content:
    storage:
      create-root: ''
      root-folder: ''
  database-schema-update: ''
  experimental:
    debugger:
      enabled: ''
  form-field-validation-enabled: ''
  history-level: ''
  idm:
    app:
      admin:
        email: ''
        first-name: ''
        last-name: ''
        password: ''
        user-id: ''
      bootstrap: true
      rest-enabled: true
      security:
        cookie:
          domain: ''
          max-age: 2678400
          refresh-age: 86400
        remember-me-key: 'testKey'
        user-validity-period: 30000
    enabled: ''
    ldap:
      attribute:
        email: ''
        first-name: ''
        group-id: ''
        group-name: ''
        last-name: ''
        user-id: ''
      base-dn: ''
      cache:
        group-size: ''
      enabled: ''
      password: ''
      port: ''
      query:
        all-groups: ''
        all-users: ''
        groups-for-user: ''
        user-by-full-name-like: ''
        user-by-id: ''
      server: ''
      user: ''
    password-encoder: ''
  mail:
    server:
      host: ''
      password: ''
      port: ''
      ssl-port: ''
      use-ssl: ''
      use-tls: ''
      username: ''
  modeler:
    app:
      data-source-prefix: ''
      rest-enabled: ''
  process:
    definition-cache-limit: -1
    servlet:
      name: ${spring.application.name}
      path: /wlxx-flowable
  rest:
    app:
      authentication-mode: ''
  task:
    app:
      rest-enabled: true
#message:
#  reloading:
#    enabled: true
#spring:
#  datasource:
#    driver-class-name: ''
#    hikari:
#      connection-test-query: ''
#      connection-timeout: ''
#      idle-timeout: ''
#      max-lifetime: ''
#      maximum-pool-size: ''
#      minimum-idle: ''
#    jndi-name: ''
#    password: ''
#    url: ''
#    username: ''
#  servlet:
#    multipart:
#      max-file-size: ''
