server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
spring:
  batch:
    job:
      enabled: false
  jmx:
    unique-names: true
    default-domain: ${spring.application.name}
  aop:
    proxy-target-class: false
    auto: false
  banner:
    location: classpath:/org/flowable/spring/boot/flowable-banner.txt
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_flowable?characterEncoding=UTF-8
    username: root
    password: xiao
    hikari:
      poolName: ${spring.application.name}
      maxLifetime: 600000
      idleTimeout: 300000
      minimumIdle: 10
      maximumPoolSize: 50
  task:
    execution:
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
      thread-name-prefix: flowable-ui-task-Executor-
    scheduling:
      pool:
        size: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
      roles: access-admin
flowable:
  common:
    app:
      role-prefix: ''
      idm-admin:
        user: admin
        password: test
  process:
    definition-cache-limit: 512
    async:
      executor:
        default-async-job-acquire-wait-time: PT5S
        default-timer-job-acquire-wait-time: PT5S
  cmmn:
    async:
      executor:
        default-async-job-acquire-wait-time: PT5S
        default-timer-job-acquire-wait-time: PT5S
  content:
    storage:
      root-folder: data/
      create-root: true
  experimental:
    debugger:
      enabled: false
  task:
    app:
      rest-enabled: true
  rest:
    app:
      authentication-mode: verify-privilege
  form-field-validation-enabled: false
  admin:
    app:
      security:
        encryption:
          credentials-i-v-spec: j8kdO2hejA9lKmm6
          credentials-secret-spec: 9FGl73ngxcOoJvmL
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: Test
        last-name: Administrator
        email: test-admin@example-domain.tld
