spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: public
      gateway:
        discovery:
          locator:
            enabled: true  #是否与服务注册于发现组件结合，通过 serviceId 转发到具体的服务
            lower-case-service-id: true
        routes:
          - id: gateway-service-provider
            uri: lb://testprovider
            predicates:
              - Path=/provider/**
          - id: gateway-service-consumer
            uri: lb://testconsumer
            predicates:
              - Path=/consumer/**

server:
  port: 18000