spring:
  application:
    name: wlxx-app
  datasource:
    spring:
      datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:h2:mem:test
    url: jdbc:mysql://localhost:3306/framework?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: xiao
#    多数据源配置
#    hikari:
#      # HikariPool 需要使用 jdbc-url
#      wlxx:
#        jdbc-url: jdbc:mysql://localhost:3306/wlxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: xiao
#      user:
#        jdbc-url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: xiao
#      framework:
#        jdbc-url: jdbc:mysql://localhost:3306/framework?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: xiao
  devtools:
    remote:
      restart:
        enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#  关闭校验BPS检查bpmn文件的校验
#  activiti:
#    check-process-definitions: false
#  main:
#    allow-bean-definition-overriding: true
  main:
    banner-mode: console
#    TODO 这个有什么用
#    register-shutdown-hook: true
server:
  port: 8090

eureka:
#  监控检查
#  healthcheck:
#    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
#    关闭服务端注册
    enabled: false
    service-url:
      defaultZone: http://admin:admin@localhost:12000/eureka

logging:
  level:
    root: info

#关闭activiti安全验证
security:
  basic:
    enabled: false

mybatis-plus:
  global-config:
    refresh: true
#    activeRecord: true FIXME 这个怎么开启？是否是因为分离式模块导致无法编译到entity？activeRecord模式不支持hikari多数据源？
#    db-config:
#      id-type: 2 #主键类型  全局唯一ID，内容为空自动填充（默认配置），对应数字 2
#      field-strategy: 1 #字段策略 IGNORED-0:"忽略判断",NOT_NULL-1:"非 NULL 判断"),NOT_EMPTY-2:"非空判断"
#      db-column-underline: true #表名、字段名、是否使用下划线命名
#      capital-mode: false #是否大写命名
#      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除注入器
#      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)
#      logic-delete-value: 1 #逻辑已删除值(默认为 1)
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true #下换线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl