spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_camunda?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: demo
      password: demo
#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    filter:
      create: All tasks
  bpm:
    authorization:
      enabled: false
#    database:
#      table-prefix:
#      schema-update: true
#      type: mysql
#      schema-name: db_camunda
#      jdbc-batch-processing: true

logging:
  level:
    com.xzg.wlxx.camunda: debug
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
    - group: 'camunda'
      paths-to-match: '/**'
      packages-to-scan: org.camunda.bpm
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn